name: "Check formatting"
on:
  - pull_request
  - push

jobs:
  formatters:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3

      - name: "markdownlint"
        uses: DavidAnson/markdownlint-cli2-action@v20

      - name: prettier
        uses: creyD/prettier_action@v4.6
        with:
          dry: True
          prettier_options: --check

      - name: "sh-checker"
        uses: luizm/action-sh-checker@master
        env:
          SHELLCHECK_OPTS: -e SC1071
          SHFMT_OPTS: -s
